### ISSUE TITLE
Patch in sane window handling in multi-screen setup

### ISSUE THREAD

**Issue by dscho** [imagej/ij1-patcher#2]
It is a good idea to pop up a dialog on the same screen as the foreground window.

The best idea is probably to
1. determine which window is focused (we should iterate through `IJ.getInstance()`, `IJ.getImage().getWindow()` and all the `WindowManager.getNonImageWindows()` and test via `isFocused()` whether they are in the foreground
2. get their [`GraphicsConfiguration`](http://docs.oracle.com/javase/7/docs/api/java/awt/GraphicsConfiguration.html)
3. inject that configuration as last parameter to the [`Dialog` constructor](http://docs.oracle.com/javase/7/docs/api/java/awt/Dialog.html#Dialog%28java.awt.Frame,%20java.lang.String,%20boolean,%20java.awt.GraphicsConfiguration%29) instead of [the one that is actually defined by ImageJ 1.x](https://github.com/imagej/ImageJA/blob/5df63d3801bbcc227c62b9188ea77884b358350f/src/main/java/ij/gui/GenericDialog.java#L93).

Of course, this can be done only as long as we're not about to activate headless mode.

It is highly likely that ImageJ 1.x will adopt a slightly divergent version of what I wrote up above; We will need to watch out for that and fix as necessary.

This issue is based on https://github.com/imagej/imagej/issues/32.

**Comment by ctrueden** [comment]
Some work was contributed to ImageJ1 upstream; see imagej/imagej1#77 and [this forum topic](https://forum.image.sc/t/better-support-for-multi-screen-setups-in-imagej-fiji/24990).
