### ISSUE TITLE
Evaluate HeadlessGenericDialog synchronization with GenericDialog

### ISSUE THREAD

**Issue by hinerm** [imagej/ij1-patcher#35]
The ImageJ `GenericDialog` has added new public API that is not covered by `HeadlessGenericDialog`. I added these methods to the [HeadlessCompletenessTest whitelist](https://github.com/imagej/ij1-patcher/blob/ij1-patcher-0.12.0/src/test/java/net/imagej/patcher/HeadlessCompletenessTest.java#L123-141) but should probably actually add the signatures to `HeadlessGenericDialog`.

It would be good to use this opportunity to remove the rest of the whitelist, converting to instead to implementing everything but throwing exceptions when appropriate.

**Comment by dscho** [comment]
> I added these methods to the HeadlessCompletenessTest whitelist but should probably actually add the signatures to HeadlessGenericDialog.

Precisely.

> It would be good to use this opportunity to remove the rest of the whitelist, converting to instead to implementing everything but throwing exceptions when appropriate.

No, the whitelist has the methods that should *not* be overridden.

**Comment by hinerm** [comment]
@dscho That's fine with me, but could you explain what the reasoning is to decide if a method should or should not be overridden? I would at least like to document the scheme with which we decide to whitelist stuff or not.

e.g. :octopus: 
why aren't protected/package-protected methods overridden?
why wasn't `parseDouble` overridden? 
why are some AWT-land-inherited methods, e.g. `focusGained` overridden, but not, say, `textValueChanged`?

thanks!

**Comment by dscho** [comment]
> why aren't protected/package-protected methods overridden?

because they cannot be called (without reflection) from the outside.

> why wasn't parseDouble overridden?

IIRC because it works headlessly.

> why are some AWT-land-inherited methods, e.g. focusGained overridden, but not, say, textValueChanged?

I do not remember... ;-)

**Comment by hinerm** [comment]
closed by:
1aebe19691224b57dc0923c33ff17d7100946f72, 5cca8135fb3a37fc7256d54117dc3e4149354a82, 16b114a50badb801db14fd8875cd0134155f6a68
