### ISSUE TITLE
FatJarTest fails on Travis

### ISSUE THREAD

**Issue by imagejan** [imagej/ij1-patcher#46]
I remember having discussed this already, but didn't find an issue for it, except @ctrueden's [comment on gitter](https://gitter.im/imagej/imagej?at=5a429a66ffa3e37919813544).

While `FatJarTest` still passed in [build `#17`](https://travis-ci.org/imagej/ij1-patcher/builds/283953770) (on https://github.com/imagej/ij1-patcher/commit/d1ff2a5a3361db5a53b6682bcd45434b81f8bd48), it fails from [build `#18`](https://travis-ci.org/imagej/ij1-patcher/builds/316402249) (https://github.com/imagej/ij1-patcher/commit/c6adec62a4b5e545faab0bc6421278239789eebb) onward.

**Comment by ctrueden** [comment]
I believe that this was fixed a while back with 2eaf5ccae615d2ec0182fcde616e56512231e8bb, but I forgot to close out this issue.
