### ISSUE TITLE
Move more stuff from fiji-compat into the ij1-patcher

### ISSUE THREAD

**Issue by dscho** [imagej/ij1-patcher#9]
`fiji-compat` brings useful things such as the `FileDialogDecorator` and the `JFileChooserDecorator`. They are too useful to be hidden in the ImageJ distribution for the life sciences...

**Comment by ctrueden** [comment]
Closing as YAGNI. For backwards compatibility, the classes _are_ still available, as part of the main fiji/fiji artifact (fiji/fiji-compat was retired, with its classes merged to fiji/fiji). And we can still move things from there as needed to foster reuse without dependency bloat. But in practice over the past few years, nobody I know of is using them for current work.
